[package]
name = "hestia"
version = "0.1.0"
edition = "2021"

[lib]
name = "hestia"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
polars = { version = "0.27.2", features = ["lazy", "parquet"] }
arrow2 = "0.17.2"